### ISSUE TITLE
Consider making references to other projects explicit

### ISSUE THREAD

**Issue by zeroXten** [threatspec/threatspec#27]
At the moment threatspec which recursively (using globs) check each path in paths and check for the existence of a threatspec.yaml file. If found, it loads configuration file and the library files etc. It then will recursively search that repo's paths. It then repeats the search when looking for source files.
This is pretty inefficient, but it's also hard to understand the relationship between repositories - you have to search through all of the repos first. By making the relationship with other repos more explicit, this would allow the file processing code to be cleaned up, but could also allow for visualisations of that relationship. It is also conceptually a bit cleaner.

Eg
```
project:
  name: My ThreatSpec Project
  description: A description goes here
import: # Load threatmodel library files from these repositories during parsing and reporting
  - path/to/repository1
  - path/to/repository2
paths:
  - path/to/source1
  - path/to/source2
```
